// Tradução (pt-BR) dos nomes kebab-case dos ícones lucide usados em `sidebarIcons.ts`.
// Fonte única de rótulo exibido/buscável no `IconColorPicker` — permite buscar "mala" em vez
// de "backpack". Ícone sem entrada aqui cai no próprio nome kebab-case como fallback.
export const ICON_LABEL_PT: Record<string, string> = {
  'activity': 'atividade', 'airplay': 'transmitir tela', 'alarm-clock': 'despertador',
  'album': 'álbum', 'anchor': 'âncora', 'apple': 'maçã', 'archive': 'arquivar',
  'arrow-right': 'seta direita', 'arrow-up-right': 'seta diagonal', 'award': 'prêmio',
  'axe': 'machado', 'baby': 'bebê', 'backpack': 'mochila', 'badge': 'selo',
  'badge-check': 'selo verificado', 'bag': 'bolsa', 'banana': 'banana', 'banknote': 'cédula',
  'bar-chart-2': 'gráfico de barras', 'battery': 'bateria', 'beaker': 'béquer', 'beer': 'cerveja',
  'bell': 'sino', 'bike': 'bicicleta', 'binoculars': 'binóculo', 'bird': 'pássaro',
  'bitcoin': 'bitcoin', 'blender': 'liquidificador', 'blueprint': 'planta baixa',
  'bluetooth': 'bluetooth', 'boat': 'barco', 'bold': 'negrito', 'bomb': 'bomba',
  'book': 'livro', 'book-open': 'livro aberto', 'bookmark': 'marcador', 'bottle': 'garrafa',
  'box': 'caixa', 'brackets': 'colchetes', 'briefcase': 'maleta', 'brush': 'pincel',
  'bug': 'inseto', 'building': 'prédio', 'building-2': 'edifício', 'bus': 'ônibus',
  'cake': 'bolo', 'calculator': 'calculadora', 'calendar': 'calendário', 'camera': 'câmera',
  'candy': 'doce', 'car': 'carro', 'carrot': 'cenoura', 'cart': 'carrinho',
  'check-circle': 'círculo de confirmação', 'check-circle-2': 'confirmado',
  'checklist': 'lista de verificação', 'chef-hat': 'chapéu de chef', 'circle': 'círculo',
  'clapper': 'claquete', 'clapperboard': 'claquete de cinema', 'clipboard': 'prancheta',
  'clipboard-list': 'prancheta com lista', 'clock': 'relógio', 'clock-3': 'relógio (3h)',
  'clothing': 'roupa', 'cloud': 'nuvem', 'cloud-rain': 'nuvem de chuva', 'clover': 'trevo',
  'code': 'código', 'code-2': 'código-fonte', 'coffee': 'café', 'cog': 'engrenagem',
  'coins': 'moedas', 'compass': 'bússola', 'construction': 'construção', 'contact': 'contato',
  'cookie': 'biscoito', 'copyright': 'direitos autorais', 'couch': 'sofá', 'cpu': 'processador',
  'credit-card': 'cartão de crédito', 'crown': 'coroa', 'cup': 'copo', 'database': 'banco de dados',
  'diamond': 'diamante', 'dice': 'dado', 'dice-1': 'dado (1)', 'dice-5': 'dado (5)',
  'disc': 'disco', 'door-open': 'porta aberta', 'download': 'baixar', 'drama': 'teatro',
  'dress': 'vestido', 'drill': 'furadeira', 'droplet': 'gota', 'drum': 'tambor',
  'ear': 'orelha', 'egg': 'ovo', 'equal': 'igual', 'eye': 'olho', 'factory': 'fábrica',
  'fan': 'ventilador', 'feather': 'pena', 'file': 'arquivo', 'file-text': 'arquivo de texto',
  'film': 'filme', 'filter': 'filtro', 'fingerprint': 'impressão digital', 'first-aid': 'primeiros socorros',
  'fish': 'peixe', 'flag': 'bandeira', 'flame': 'chama', 'flashlight': 'lanterna',
  'flask': 'frasco', 'flask-conical': 'frasco cônico', 'flower': 'flor', 'flower-2': 'flor (2)',
  'folder': 'pasta', 'folder-open': 'pasta aberta', 'footprints': 'pegadas', 'fuel': 'combustível',
  'gamepad': 'controle de jogo', 'gamepad-2': 'controle de jogo (2)', 'gauge': 'velocímetro',
  'gear': 'engrenagem', 'gem': 'gema', 'ghost': 'fantasma', 'gift': 'presente',
  'git-branch': 'ramificação git', 'git-commit': 'commit git', 'github': 'github', 'gitlab': 'gitlab',
  'glass': 'copo', 'glass-water': 'copo d’água', 'globe': 'globo', 'graduation-cap': 'capelo de formatura',
  'grape': 'uva', 'grapes': 'cacho de uvas', 'grid-3x3': 'grade', 'hammer': 'martelo',
  'hand': 'mão', 'handbag': 'bolsa de mão', 'handshake': 'aperto de mão', 'hard-hat': 'capacete',
  'headphones': 'fone de ouvido', 'heart': 'coração', 'heart-handshake': 'acordo de coração',
  'help-circle': 'ajuda', 'helping-hand': 'mão que ajuda', 'hexagon': 'hexágono', 'home': 'casa',
  'home-heart': 'casa com coração', 'hourglass': 'ampulheta', 'ice-cream': 'sorvete',
  'image': 'imagem', 'image-plus': 'adicionar imagem', 'inbox': 'caixa de entrada',
  'inbox-0': 'caixa de entrada vazia', 'key': 'chave', 'keyboard': 'teclado', 'lamp': 'luminária',
  'landmark': 'monumento', 'laptop': 'notebook', 'layers': 'camadas', 'leaf': 'folha',
  'leaf-2': 'folha (2)', 'lemon': 'limão', 'life-buoy': 'boia salva-vidas', 'lightbulb': 'lâmpada',
  'link': 'link', 'list': 'lista', 'list-checks': 'lista com marcações', 'lock': 'cadeado',
  'luggage': 'mala de viagem', 'magnet': 'ímã', 'mail': 'e-mail', 'map': 'mapa',
  'map-pin': 'alfinete de mapa', 'martini': 'coquetel', 'medal': 'medalha', 'megaphone': 'megafone',
  'messages-square': 'mensagens', 'mic': 'microfone', 'mic-off': 'microfone desligado',
  'milestone': 'marco', 'monitor': 'monitor', 'moon': 'lua', 'mountain': 'montanha',
  'mouse-pointer': 'cursor do mouse', 'music': 'música', 'music-2': 'música (2)',
  'navigation': 'navegação', 'network': 'rede', 'newspaper': 'jornal', 'notebook': 'caderno',
  'notepad': 'bloco de notas', 'package': 'pacote', 'paint-bucket': 'balde de tinta',
  'palette': 'paleta', 'panda': 'panda', 'paperclip': 'clipe de papel', 'parking-circle': 'estacionamento',
  'party-popper': 'confete', 'pen': 'caneta', 'pen-tool': 'ferramenta caneta', 'pencil': 'lápis',
  'percent': 'porcentagem', 'phone': 'telefone', 'phone-off': 'telefone desligado',
  'piano': 'piano', 'pie-chart': 'gráfico de pizza', 'piggy-bank': 'cofrinho', 'pill': 'comprimido',
  'pin': 'alfinete', 'pizza': 'pizza', 'plane': 'avião', 'plant': 'planta', 'play': 'reproduzir',
  'play-circle': 'reproduzir (círculo)', 'plug': 'plugue', 'power': 'energia', 'presentation': 'apresentação',
  'printer': 'impressora', 'puzzle': 'quebra-cabeça', 'radar': 'radar', 'radio': 'rádio',
  'rocket': 'foguete', 'route': 'rota', 'rss': 'rss', 'ruler': 'régua', 'sandwich': 'sanduíche',
  'satellite': 'satélite', 'save': 'salvar', 'scale': 'balança', 'school': 'escola',
  'scissors': 'tesoura', 'screen-share': 'compartilhar tela', 'send': 'enviar', 'server': 'servidor',
  'settings': 'configurações', 'shapes': 'formas', 'share-2': 'compartilhar', 'shield': 'escudo',
  'shield-alert': 'escudo de alerta', 'ship': 'navio', 'shirt': 'camisa', 'shoe': 'sapato',
  'shopping-bag': 'sacola de compras', 'shopping-cart': 'carrinho de compras', 'shovel': 'pá',
  'shrub': 'arbusto', 'shuffle': 'aleatório', 'signal': 'sinal', 'siren': 'sirene',
  'skull': 'caveira', 'smartphone': 'celular', 'smile': 'sorriso', 'snowflake': 'floco de neve',
  'sofa': 'sofá', 'sparkles': 'brilhos', 'speaker': 'alto-falante', 'sprout': 'broto',
  'square': 'quadrado', 'square-activity': 'atividade (quadrado)', 'square-check': 'marcado',
  'stamp': 'carimbo', 'star': 'estrela', 'store': 'loja', 'sun': 'sol', 'sunrise': 'nascer do sol',
  'sunset': 'pôr do sol', 'swords': 'espadas', 'syringe': 'seringa', 'table': 'tabela',
  'tag': 'etiqueta', 'target': 'alvo', 'tent': 'barraca', 'terminal': 'terminal',
  'thermometer': 'termômetro', 'ticket': 'ingresso', 'tickets': 'ingressos', 'timer': 'temporizador',
  'todo': 'tarefa', 'tomato': 'tomate', 'tool': 'ferramenta', 'tools': 'ferramentas',
  'tornado': 'tornado', 'tractor': 'trator', 'train': 'trem', 'train-track': 'trilho de trem',
  'trash-2': 'lixeira', 'tree': 'árvore', 'tree-pine': 'pinheiro', 'trending-up': 'em alta',
  'triangle': 'triângulo', 'trophy': 'troféu', 'truck': 'caminhão', 'tv': 'televisão',
  'umbrella': 'guarda-chuva', 'unlock': 'destravar', 'upload': 'enviar arquivo', 'user': 'usuário',
  'user-check': 'usuário verificado', 'user-plus': 'adicionar usuário', 'users': 'usuários',
  'utensils': 'talheres', 'video': 'vídeo', 'voicemail': 'correio de voz', 'volume': 'volume',
  'volume-2': 'volume alto', 'wallet': 'carteira', 'wand': 'varinha', 'wand-2': 'varinha mágica',
  'watch': 'relógio de pulso', 'waves': 'ondas', 'webcam': 'webcam', 'wheat': 'trigo',
  'wifi': 'wi-fi', 'wifi-off': 'wi-fi desligado', 'wind': 'vento', 'wine': 'vinho',
  'wrench': 'chave inglesa', 'x-circle': 'cancelar', 'zap': 'raio', 'zap-off': 'raio desligado',
  'grid-3x3': 'grade',
}

/** Rótulo em português do ícone (kebab-case) — cai no próprio nome se não houver tradução. */
export function iconLabel(name: string): string {
  return ICON_LABEL_PT[name] ?? name
}
