// Tradução (pt-BR) dos nomes kebab-case dos ícones lucide usados em `sidebarIcons.ts`.
// Fonte única de rótulo exibido/buscável no `IconColorPicker` — permite buscar "mala" em vez
// de "backpack". Ícone sem entrada aqui cai no próprio nome kebab-case como fallback.
export const ICON_LABEL_PT: Record<string, string> = {
  'activity': 'atividade', 'airplay': 'transmitir tela', 'alarm-clock': 'despertador',
  'album': 'álbum', 'anchor': 'âncora', 'apple': 'maçã', 'archive': 'arquivar',
  'arrow-right': 'seta direita', 'arrow-up-right': 'seta diagonal', 'award': 'prêmio',
  'axe': 'machado', 'baby': 'bebê', 'backpack': 'mochila', 'badge': 'selo',
  'badge-check': 'selo verificado', 'bag': 'bolsa', 'banana': 'banana', 'banknote': 'cédula',
  'bar-chart-2': 'gráfico de barras', 'battery': 'bateria', 'beaker': 'béquer', 'beer': 'cerveja',
  'bell': 'sino', 'bike': 'bicicleta', 'binoculars': 'binóculo', 'bird': 'pássaro',
  'bitcoin': 'bitcoin', 'blender': 'liquidificador', 'blueprint': 'planta baixa',
  'bluetooth': 'bluetooth', 'boat': 'barco', 'bold': 'negrito', 'bomb': 'bomba',
  'book': 'livro', 'book-open': 'livro aberto', 'bookmark': 'marcador', 'bottle': 'garrafa',
  'box': 'caixa', 'brackets': 'colchetes', 'briefcase': 'maleta', 'brush': 'pincel',
  'bug': 'inseto', 'building': 'prédio', 'building-2': 'edifício', 'bus': 'ônibus',
  'cake': 'bolo', 'calculator': 'calculadora', 'calendar': 'calendário', 'camera': 'câmera',
  'candy': 'doce', 'car': 'carro', 'carrot': 'cenoura', 'cart': 'carrinho',
  'check-circle': 'círculo de confirmação', 'check-circle-2': 'confirmado',
  'checklist': 'lista de verificação', 'chef-hat': 'chapéu de chef', 'circle': 'círculo',
  'clapper': 'claquete', 'clapperboard': 'claquete de cinema', 'clipboard': 'prancheta',
  'clipboard-list': 'prancheta com lista', 'clock': 'relógio', 'clock-3': 'relógio (3h)',
  'clothing': 'roupa', 'cloud': 'nuvem', 'cloud-rain': 'nuvem de chuva', 'clover': 'trevo',
  'code': 'código', 'code-2': 'código-fonte', 'coffee': 'café', 'cog': 'engrenagem',
  'coins': 'moedas', 'compass': 'bússola', 'construction': 'construção', 'contact': 'contato',
  'cookie': 'biscoito', 'copyright': 'direitos autorais', 'couch': 'sofá', 'cpu': 'processador',
  'credit-card': 'cartão de crédito', 'crown': 'coroa', 'cup': 'copo', 'database': 'banco de dados',
  'diamond': 'diamante', 'dice': 'dado', 'dice-1': 'dado (1)', 'dice-5': 'dado (5)',
  'disc': 'disco', 'door-open': 'porta aberta', 'download': 'baixar', 'drama': 'teatro',
  'dress': 'vestido', 'drill': 'furadeira', 'droplet': 'gota', 'drum': 'tambor',
  'ear': 'orelha', 'egg': 'ovo', 'equal': 'igual', 'eye': 'olho', 'factory': 'fábrica',
  'fan': 'ventilador', 'feather': 'pena', 'file': 'arquivo', 'file-text': 'arquivo de texto',
  'film': 'filme', 'filter': 'filtro', 'fingerprint': 'impressão digital', 'first-aid': 'primeiros socorros',
  'fish': 'peixe', 'flag': 'bandeira', 'flame': 'chama', 'flashlight': 'lanterna',
  'flask': 'frasco', 'flask-conical': 'frasco cônico', 'flower': 'flor', 'flower-2': 'flor (2)',
  'folder': 'pasta', 'folder-open': 'pasta aberta', 'footprints': 'pegadas', 'fuel': 'combustível',
  'gamepad': 'controle de jogo', 'gamepad-2': 'controle de jogo (2)', 'gauge': 'velocímetro',
  'gear': 'engrenagem', 'gem': 'gema', 'ghost': 'fantasma', 'gift': 'presente',
  'git-branch': 'ramificação git', 'git-commit': 'commit git', 'github': 'github', 'gitlab': 'gitlab',
  'glass': 'copo', 'glass-water': 'copo d’água', 'globe': 'globo', 'graduation-cap': 'capelo de formatura',
  'grape': 'uva', 'grapes': 'cacho de uvas', 'grid-3x3': 'grade', 'hammer': 'martelo',
  'hand': 'mão', 'handbag': 'bolsa de mão', 'handshake': 'aperto de mão', 'hard-hat': 'capacete',
  'headphones': 'fone de ouvido', 'heart': 'coração', 'heart-handshake': 'acordo de coração',
  'help-circle': 'ajuda', 'helping-hand': 'mão que ajuda', 'hexagon': 'hexágono', 'home': 'casa',
  'home-heart': 'casa com coração', 'hourglass': 'ampulheta', 'ice-cream': 'sorvete',
  'image': 'imagem', 'image-plus': 'adicionar imagem', 'inbox': 'caixa de entrada',
  'inbox-0': 'caixa de entrada vazia', 'key': 'chave', 'keyboard': 'teclado', 'lamp': 'luminária',
  'landmark': 'monumento', 'laptop': 'notebook', 'layers': 'camadas', 'leaf': 'folha',
  'leaf-2': 'folha (2)', 'lemon': 'limão', 'life-buoy': 'boia salva-vidas', 'lightbulb': 'lâmpada',
  'link': 'link', 'list': 'lista', 'list-checks': 'lista com marcações', 'lock': 'cadeado',
  'luggage': 'mala de viagem', 'magnet': 'ímã', 'mail': 'e-mail', 'map': 'mapa',
  'map-pin': 'alfinete de mapa', 'martini': 'coquetel', 'medal': 'medalha', 'megaphone': 'megafone',
  'messages-square': 'mensagens', 'mic': 'microfone', 'mic-off': 'microfone desligado',
  'milestone': 'marco', 'monitor': 'monitor', 'moon': 'lua', 'mountain': 'montanha',
  'mouse-pointer': 'cursor do mouse', 'music': 'música', 'music-2': 'música (2)',
  'navigation': 'navegação', 'network': 'rede', 'newspaper': 'jornal', 'notebook': 'caderno',
  'notepad': 'bloco de notas', 'package': 'pacote', 'paint-bucket': 'balde de tinta',
  'palette': 'paleta', 'panda': 'panda', 'paperclip': 'clipe de papel', 'parking-circle': 'estacionamento',
  'party-popper': 'confete', 'pen': 'caneta', 'pen-tool': 'ferramenta caneta', 'pencil': 'lápis',
  'percent': 'porcentagem', 'phone': 'telefone', 'phone-off': 'telefone desligado',
  'piano': 'piano', 'pie-chart': 'gráfico de pizza', 'piggy-bank': 'cofrinho', 'pill': 'comprimido',
  'pin': 'alfinete', 'pizza': 'pizza', 'plane': 'avião', 'plant': 'planta', 'play': 'reproduzir',
  'play-circle': 'reproduzir (círculo)', 'plug': 'plugue', 'power': 'energia', 'presentation': 'apresentação',
  'printer': 'impressora', 'puzzle': 'quebra-cabeça', 'radar': 'radar', 'radio': 'rádio',
  'rocket': 'foguete', 'route': 'rota', 'rss': 'rss', 'ruler': 'régua', 'sandwich': 'sanduíche',
  'satellite': 'satélite', 'save': 'salvar', 'scale': 'balança', 'school': 'escola',
  'scissors': 'tesoura', 'screen-share': 'compartilhar tela', 'send': 'enviar', 'server': 'servidor',
  'settings': 'configurações', 'shapes': 'formas', 'share-2': 'compartilhar', 'shield': 'escudo',
  'shield-alert': 'escudo de alerta', 'ship': 'navio', 'shirt': 'camisa', 'shoe': 'sapato',
  'shopping-bag': 'sacola de compras', 'shopping-cart': 'carrinho de compras', 'shovel': 'pá',
  'shrub': 'arbusto', 'shuffle': 'aleatório', 'signal': 'sinal', 'siren': 'sirene',
  'skull': 'caveira', 'smartphone': 'celular', 'smile': 'sorriso', 'snowflake': 'floco de neve',
  'sofa': 'sofá', 'sparkles': 'brilhos', 'speaker': 'alto-falante', 'sprout': 'broto',
  'square': 'quadrado', 'square-activity': 'atividade (quadrado)', 'square-check': 'marcado',
  'stamp': 'carimbo', 'star': 'estrela', 'store': 'loja', 'sun': 'sol', 'sunrise': 'nascer do sol',
  'sunset': 'pôr do sol', 'swords': 'espadas', 'syringe': 'seringa', 'table': 'tabela',
  'tag': 'etiqueta', 'target': 'alvo', 'tent': 'barraca', 'terminal': 'terminal',
  'thermometer': 'termômetro', 'ticket': 'ingresso', 'tickets': 'ingressos', 'timer': 'temporizador',
  'todo': 'tarefa', 'tomato': 'tomate', 'tool': 'ferramenta', 'tools': 'ferramentas',
  'tornado': 'tornado', 'tractor': 'trator', 'train': 'trem', 'train-track': 'trilho de trem',
  'trash-2': 'lixeira', 'tree': 'árvore', 'tree-pine': 'pinheiro', 'trending-up': 'em alta',
  'triangle': 'triângulo', 'trophy': 'troféu', 'truck': 'caminhão', 'tv': 'televisão',
  'umbrella': 'guarda-chuva', 'unlock': 'destravar', 'upload': 'enviar arquivo', 'user': 'usuário',
  'user-check': 'usuário verificado', 'user-plus': 'adicionar usuário', 'users': 'usuários',
  'utensils': 'talheres', 'video': 'vídeo', 'voicemail': 'correio de voz', 'volume': 'volume',
  'volume-2': 'volume alto', 'wallet': 'carteira', 'wand': 'varinha', 'wand-2': 'varinha mágica',
  'watch': 'relógio de pulso', 'waves': 'ondas', 'webcam': 'webcam', 'wheat': 'trigo',
  'wifi': 'wi-fi', 'wifi-off': 'wi-fi desligado', 'wind': 'vento', 'wine': 'vinho',
  'wrench': 'chave inglesa', 'x-circle': 'cancelar', 'zap': 'raio', 'zap-off': 'raio desligado',
  // ── Ampliação de 01/08/2026 ─────────────────────────────────────────────
  // Rótulos dos ícones adicionados junto com as 10 categorias novas. Sem entrada
  // aqui o ícone só seria encontrado pelo nome em inglês.
  'arrow-left': 'seta esquerda', 'arrow-up': 'seta acima', 'arrow-down': 'seta abaixo',
  'circle-check': 'círculo confirmado', 'circle-x': 'círculo cancelado', 'eye-off': 'ocultar',
  'circle-help': 'ajuda', 'x': 'fechar', 'check': 'confirmar',
  'plus': 'adicionar', 'minus': 'remover', 'refresh-cw': 'atualizar',
  'rotate-cw': 'girar', 'maximize': 'maximizar', 'minimize': 'minimizar',
  'move': 'mover', 'expand': 'expandir', 'shrink': 'encolher',
  'zoom-in': 'aproximar', 'zoom-out': 'afastar', 'sliders-horizontal': 'controles',
  'toggle-left': 'chave desligada', 'toggle-right': 'chave ligada', 'infinity': 'infinito',
  'asterisk': 'asterisco', 'more-horizontal': 'mais opções', 'more-vertical': 'mais opções vertical',
  'menu': 'menu', 'chevron-right': 'avançar', 'chevron-down': 'expandir para baixo',
  'external-link': 'link externo', 'corner-down-right': 'desvio', 'repeat': 'repetir',
  'trending-down': 'queda', 'receipt': 'recibo', 'hand-coins': 'pagamento na mão',
  'wallet-cards': 'carteira de cartões', 'line-chart': 'gráfico de linha', 'bar-chart': 'gráfico de barras',
  'area-chart': 'gráfico de área', 'circle-dollar-sign': 'moeda dólar', 'dollar-sign': 'cifrão',
  'euro': 'euro', 'briefcase-business': 'maleta de negócios', 'warehouse': 'galpão',
  'ticket-percent': 'cupom de desconto', 'tags': 'etiquetas', 'badge-percent': 'selo de desconto',
  'bell-ring': 'sino tocando', 'mail-open': 'e-mail aberto', 'message-circle': 'mensagem',
  'message-square': 'balão de mensagem', 'phone-call': 'chamada', 'volume-x': 'mudo',
  'at-sign': 'arroba', 'reply': 'responder', 'forward': 'encaminhar',
  'video-off': 'vídeo desligado', 'podcast': 'podcast', 'antenna': 'antena',
  'radio-tower': 'torre de rádio', 'captions': 'legendas', 'languages': 'idiomas',
  'user-minus': 'remover pessoa', 'user-x': 'bloquear pessoa', 'users-round': 'grupo de pessoas',
  'user-round': 'pessoa', 'circle-user': 'perfil', 'person-standing': 'pessoa em pé',
  'accessibility': 'acessibilidade', 'hand-heart': 'cuidado', 'calendar-check': 'data confirmada',
  'calendar-days': 'calendário mensal', 'calendar-clock': 'agendamento', 'clipboard-check': 'prancheta conferida',
  'list-todo': 'lista de afazeres', 'notebook-pen': 'caderno de anotações', 'square-check-big': 'caixa marcada',
  'circle-check-big': 'círculo marcado', 'kanban': 'quadro kanban', 'columns-3': 'colunas',
  'rows-3': 'linhas', 'filter-x': 'limpar filtro', 'history': 'histórico',
  'calendar-plus': 'novo evento', 'timer-reset': 'reiniciar cronômetro', 'bell-plus': 'novo lembrete',
  'git-merge': 'mesclar', 'git-pull-request': 'solicitação de merge', 'cloud-download': 'baixar da nuvem',
  'cloud-upload': 'enviar para a nuvem', 'hard-drive': 'disco rígido', 'memory-stick': 'memória',
  'binary': 'binário', 'bot': 'robô', 'container': 'contêiner',
  'qr-code': 'código qr', 'scan': 'escanear', 'barcode': 'código de barras',
  'usb': 'usb', 'cable': 'cabo', 'router': 'roteador',
  'bed': 'cama', 'lamp-desk': 'luminária de mesa', 'armchair': 'poltrona',
  'blinds': 'persiana', 'bath': 'banheira', 'shower-head': 'chuveiro',
  'washing-machine': 'máquina de lavar', 'refrigerator': 'geladeira', 'microwave': 'micro-ondas',
  'trash': 'lixeira', 'door-closed': 'porta fechada', 'picture-in-picture': 'janela flutuante',
  'frame': 'moldura', 'cloud-snow': 'nuvem de neve', 'cloud-lightning': 'raio',
  'trees': 'árvores', 'rainbow': 'arco-íris', 'sun-dim': 'sol fraco',
  'sun-medium': 'sol médio', 'haze': 'neblina', 'thermometer-sun': 'calor',
  'thermometer-snowflake': 'frio', 'shell': 'concha', 'squirrel': 'esquilo',
  'rat': 'rato', 'turtle': 'tartaruga', 'rabbit': 'coelho',
  'dog': 'cachorro', 'cat': 'gato', 'bone': 'osso',
  'paw-print': 'pegada de pata', 'milk': 'leite', 'cup-soda': 'copo de refrigerante',
  'salad': 'salada', 'soup': 'sopa', 'ham': 'presunto',
  'beef': 'carne', 'croissant': 'croissant', 'donut': 'rosquinha',
  'popcorn': 'pipoca', 'citrus': 'cítrico', 'dessert': 'sobremesa',
  'cooking-pot': 'panela', 'utensils-crossed': 'talheres cruzados', 'train-front': 'trem',
  'sailboat': 'veleiro', 'caravan': 'trailer', 'mountain-snow': 'montanha nevada',
  'palmtree': 'coqueiro', 'signpost': 'placa de direção', 'bed-double': 'cama de casal',
  'plane-takeoff': 'decolagem', 'plane-landing': 'pouso', 'tram-front': 'bonde',
  'mic-vocal': 'microfone de mão', 'guitar': 'guitarra', 'projector': 'projetor',
  'camera-off': 'câmera desligada', 'pause': 'pausar', 'skip-forward': 'avançar faixa',
  'skip-back': 'voltar faixa', 'repeat-2': 'repetir tudo', 'list-music': 'playlist',
  'audio-lines': 'ondas de áudio', 'heart-pulse': 'batimento cardíaco', 'shield-check': 'protegido',
  'stethoscope': 'estetoscópio', 'brain': 'cérebro', 'dna': 'dna',
  'microscope': 'microscópio', 'test-tube': 'tubo de ensaio', 'hospital': 'hospital',
  'ambulance': 'ambulância', 'cross': 'cruz', 'triangle-alert': 'alerta',
  'octagon-alert': 'alerta grave', 'glasses': 'óculos', 'forklift': 'empilhadeira',
  'brick-wall': 'parede de tijolos', 'fence': 'cerca', 'pickaxe': 'picareta',
  'traffic-cone': 'cone de trânsito', 'weight': 'peso', 'blocks': 'blocos',
  'paint-roller': 'rolo de pintura', 'library': 'biblioteca', 'telescope': 'telescópio',
  'atom': 'átomo', 'scroll-text': 'pergaminho', 'sigma': 'somatório',
  'pi': 'pi', 'radical': 'raiz quadrada', 'arrow-down-right': 'seta diagonal baixo',
  'arrow-up-left': 'seta diagonal cima', 'arrow-down-left': 'seta diagonal esquerda', 'arrow-big-right': 'seta larga direita',
  'arrow-big-left': 'seta larga esquerda', 'chevron-up': 'recolher', 'chevron-left': 'voltar',
  'chevrons-up': 'subir tudo', 'chevrons-down': 'descer tudo', 'chevrons-left': 'anterior',
  'chevrons-right': 'próximo', 'corner-up-right': 'encaminhar canto', 'corner-down-left': 'retornar canto',
  'move-horizontal': 'mover na horizontal', 'move-vertical': 'mover na vertical', 'redo': 'refazer',
  'undo': 'desfazer', 'rotate-ccw': 'girar anti-horário', 'refresh-ccw': 'recarregar',
  'navigation-2': 'navegação', 'circle-arrow-up': 'subir', 'circle-arrow-down': 'descer',
  'clock-1': 'uma hora', 'clock-9': 'nove horas', 'alarm-clock-check': 'alarme confirmado',
  'timer-off': 'cronômetro parado', 'calendar-x': 'data cancelada', 'calendar-range': 'período',
  'file-check': 'arquivo aprovado', 'file-x': 'arquivo rejeitado', 'file-plus': 'novo arquivo',
  'files': 'arquivos', 'folder-plus': 'nova pasta', 'folder-check': 'pasta conferida',
  'book-marked': 'livro marcado', 'sticky-note': 'nota adesiva', 'copy': 'copiar',
  'file-spreadsheet': 'planilha', 'file-code': 'arquivo de código', 'file-image': 'arquivo de imagem',
  'file-audio': 'arquivo de áudio', 'file-video': 'arquivo de vídeo', 'file-json': 'arquivo json',
  'octagon': 'octógono', 'pentagon': 'pentágono', 'spade': 'espadas',
  'club': 'paus', 'sparkle': 'brilho', 'hash': 'cerquilha',
  'dot': 'ponto', 'grip': 'alça', 'grip-vertical': 'alça vertical',
  'grip-horizontal': 'alça horizontal', 'cloud-drizzle': 'garoa', 'cloud-fog': 'nevoeiro',
  'sun-snow': 'sol e neve', 'lock-keyhole': 'fechadura', 'key-round': 'chave redonda',
  'shield-off': 'sem proteção', 'scan-face': 'reconhecimento facial', 'ban': 'proibido',
  'circle-slash': 'bloqueado', 'alert-triangle': 'atenção', 'bell-off': 'notificações desligadas',
  'vault': 'cofre', 'workflow': 'fluxo de trabalho', 'split': 'dividir',
  'merge': 'unir', 'repeat-1': 'repetir um', 'settings-2': 'ajustes',
  'sliders-vertical': 'controles verticais', 'webhook': 'webhook', 'circuit-board': 'placa de circuito',
  'waypoints': 'pontos de rota', 'arrow-right-left': 'troca', 'frown': 'triste',
  'meh': 'indiferente', 'laugh': 'risada', 'angry': 'bravo',
  'heart-crack': 'coração partido', 'thumbs-up': 'positivo', 'thumbs-down': 'negativo',
  'annoyed': 'incomodado', 'smile-plus': 'nova reação', 'dumbbell': 'halter',
  'goal': 'gol',
}

/** Rótulo em português do ícone (kebab-case) — cai no próprio nome se não houver tradução. */
export function iconLabel(name: string): string {
  return ICON_LABEL_PT[name] ?? name
}
